# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.13.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  lint:
    docker:
      - image: circleci/node:10.13.0

    steps:
      - run: yarn lint
  
      test:
    docker:
      - image: circleci/node:10.13.0
    
    steps:
      - run: yarn test
  
  deploy:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - run:
          name: 'deploying'
          command: |
            echo $TEST_ENV
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - lint
            - test
