# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  prepare:
    docker:
      - image: circleci/node:10.13.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache
      - run: yarn install

      - save_cache:
          paths:
            - ~/repo
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
  lint:
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn lint

  test:
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn test

  deploy:
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: yarn release
      - setup_remote_docker
      - run: yarn docker:build
      - run: yarn deploy

  production:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - run: echo "Going to production!!!"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - prepare
      - lint:
          requires:
            - prepare
      - test:
          requires:
            - prepare

      - deploy:
          context: globals
          filters:
            branches:
              only:
                - master
          requires:
            - lint
            - test

      - production:
          type: approval
          filters:
            branches:
              only:
                - master
          requires:
            - deploy
