# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  prepare:
    docker:
      - image: circleci/node:10.13.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache
      - run: yarn install

      - save_cache:
          paths:
            - ~/repo
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
  lint:
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn lint

  test:
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn test

  build:
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - setup_remote_docker
      - run: yarn docker:build

  deploy:
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - add_ssh_keys:
        fingerprints:
          - 'SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.'
      - run: yarn release
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - prepare
      - lint:
          requires:
            - prepare
      - test:
          requires:
            - prepare
      - build:
          requires:
            - prepare
      - deploy:
          requires:
            - lint
            - test
